### ISSUE TITLE
Tmlanguage file missing

### ISSUE THREAD

**Issue by empathicqubit** [mfederczuk/vscode-texinfo-extension#1]
Your grammar file is missing so the project won't work correctly.

**Comment by mfederczuk** [comment]
The file exists on the [`develop`](https://github.com/mfederczuk/vscode-texinfo-extension/blob/develop/syntaxes/texinfo.tmLanguage.json) branch.

That being said, I'm not working on this project anymore, so it's not gonna be finished any time soon.

**Comment by empathicqubit** [comment]
Thanks for pointing me in the right direction :)
